"""Controlled vocabularies for ASTRA.

Every enumeration here is part of the API contract: it is exported through the
OpenAPI schema and regenerated into TypeScript in ``packages/contracts`` so the
frontend can never invent a value the backend does not know about.
"""

from __future__ import annotations

from enum import StrEnum


class ProvenanceClass(StrEnum):
    """Provenance classes per CLAUDE.md §4.2 — enforced in code, surfaced in UI.

    Every layer, table and field carries exactly one of these.
    """

    REAL_OPEN = "REAL_OPEN"
    """Real public dataset, unmodified."""

    DERIVED = "DERIVED"
    """Computed by ASTRA from REAL_OPEN inputs (slope from DEM, HAND, kernel density)."""

    SYNTHETIC_CALIBRATED = "SYNTHETIC_CALIBRATED"
    """Generated by ASTRA, statistically calibrated to the real study area, fictional."""

    DEMO_CONFIG = "DEMO_CONFIG"
    """An ASTRA-chosen threshold, weight or policy constant. Not a government rule."""


class HazardType(StrEnum):
    """The four modelled hazards (CLAUDE.md §5.1)."""

    LANDSLIDE = "LANDSLIDE"
    FLOOD = "FLOOD"
    CLOUDBURST = "CLOUDBURST"
    COASTAL_EROSION = "COASTAL_EROSION"


class ZoneClass(StrEnum):
    """Red-zone severity classes derived from the composite susceptibility surface.

    These are ASTRA analytical classifications, never statutory designations.
    """

    CRITICAL = "CRITICAL"
    ELEVATED = "ELEVATED"
    WATCH = "WATCH"
    LOW = "LOW"


class PhaseTier(StrEnum):
    """Relocation phasing tiers — the PS's exact three-tier language (§5.3)."""

    IMMEDIATE = "IMMEDIATE"
    SHORT_TERM = "SHORT_TERM"
    MEDIUM_TERM = "MEDIUM_TERM"
    NOT_PRIORITISED = "NOT_PRIORITISED"
    CAPACITY_BLOCKED = "CAPACITY_BLOCKED"
    """High risk but no feasible matched capacity — actionable intelligence, not a rank."""


class ServiceType(StrEnum):
    """Services whose per-service capacity is computed in Engine 4 (§5.4 step 3)."""

    LAND = "LAND"
    SHELTER = "SHELTER"
    WATER = "WATER"
    SANITATION = "SANITATION"
    HEALTHCARE = "HEALTHCARE"
    POWER = "POWER"
    ACCESS = "ACCESS"


class SuitabilityGate(StrEnum):
    """Hard binary gates a candidate site must pass (§5.4 step 1).

    A gate failure is reported as a named gate, never folded into a low score.
    """

    OUTSIDE_HAZARD_ZONES = "OUTSIDE_HAZARD_ZONES"
    SLOPE_BUILDABLE = "SLOPE_BUILDABLE"
    LANDCOVER_PERMITTED = "LANDCOVER_PERMITTED"
    ABOVE_FLOOD_LEVEL = "ABOVE_FLOOD_LEVEL"
    ROAD_ACCESSIBLE = "ROAD_ACCESSIBLE"


class RouteProfile(StrEnum):
    """Routing objectives returned per origin/destination pair (§5.5)."""

    FASTEST = "FASTEST"
    SAFEST = "SAFEST"


class ConfidenceBand(StrEnum):
    """Evidence confidence — orthogonal to priority, never multiplied into it (§5.2)."""

    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class SolverStatus(StrEnum):
    """Outcome of the relocation optimiser (§5.6)."""

    OPTIMAL = "OPTIMAL"
    FEASIBLE = "FEASIBLE"
    INFEASIBLE = "INFEASIBLE"
    FALLBACK = "FALLBACK"
    """Deterministic greedy fallback ran because the solver hit its time limit."""


class RunStage(StrEnum):
    """Pipeline stages emitted over SSE and rendered by the execution graph (§9)."""

    INGEST = "INGEST"
    HAZARD = "HAZARD"
    EXPOSURE_VULNERABILITY = "EXPOSURE_VULNERABILITY"
    SITE_CAPACITY = "SITE_CAPACITY"
    ROUTE_RELIABILITY = "ROUTE_RELIABILITY"
    OPTIMISATION = "OPTIMISATION"
    DECISION_BRIEF = "DECISION_BRIEF"


class RunStageStatus(StrEnum):
    """Lifecycle of a single pipeline stage. Drives node state in the graph."""

    PENDING = "PENDING"
    STARTED = "STARTED"
    PROGRESS = "PROGRESS"
    COMPLETED = "COMPLETED"
    WARNING = "WARNING"
    FAILED = "FAILED"


class EventType(StrEnum):
    """Real-time ingest event kinds accepted by POST /events (§5.8)."""

    RAINFALL_OBSERVATION = "RAINFALL_OBSERVATION"
    INCIDENT_REPORT = "INCIDENT_REPORT"
    FIELD_EVIDENCE = "FIELD_EVIDENCE"
    INFRASTRUCTURE_STATUS = "INFRASTRUCTURE_STATUS"


class DecisionState(StrEnum):
    """Human-in-the-loop state of a computed plan (§6). ASTRA never decides."""

    COMPUTED = "COMPUTED"
    UNDER_REVIEW = "UNDER_REVIEW"
    APPROVED = "APPROVED"
    OVERRIDDEN = "OVERRIDDEN"
    REQUIRES_REVIEW = "REQUIRES_REVIEW"
    """A newly ingested event invalidated part of an approved plan."""


class StructureType(StrEnum):
    """Structural typology proxy used in the vulnerability composite (§5.2)."""

    KUTCHA = "KUTCHA"
    SEMI_PUCCA = "SEMI_PUCCA"
    PUCCA = "PUCCA"


class RoadClass(StrEnum):
    """OSM-derived road classes used for free-flow speed and reliability (§5.5)."""

    NATIONAL_HIGHWAY = "NATIONAL_HIGHWAY"
    STATE_HIGHWAY = "STATE_HIGHWAY"
    DISTRICT_ROAD = "DISTRICT_ROAD"
    VILLAGE_ROAD = "VILLAGE_ROAD"
    TRACK = "TRACK"
